### ISSUE TITLE
Support for php 8

### ISSUE THREAD

**Issue by bjko** [ezsystems/ezplatform-automated-translation#21]
please support php 8 in the bundle requirements

**Comment by konradoboza** [comment]
Fixed via https://github.com/ezsystems/ezplatform-automated-translation/commit/925a0e318a7c4b7401c0d02f5c600bde8938dddf.
Released within `2.2.5`: https://github.com/ezsystems/ezplatform-automated-translation/releases/tag/v2.2.5.
